### ISSUE TITLE
【Request】Wish a style stack node

### ISSUE THREAD

**Issue by amimi818** [wolfden/ComfyUi_PromptStylers#1]
Your work is great!

Could you make a style stack node where we could select multiple styles in one node, that would be extremely easy to use.

Thanks!

A sample, FYI

<img width="286" alt="image" src="https://github.com/wolfden/ComfyUi_PromptStylers/assets/133093934/8c51fca2-1dd0-42d2-a98f-8f9eef250124">

**Comment by wolfden** [comment]
Hi and thanks, will take a look into it.  I'm far from a proficient coder ;)

**Comment by amimi818** [comment]
> Hi and thanks, will take a look into it. I'm far from a proficient coder ;)

You can refer to the "One Button Prompt" node and the "Lora Stacker" node (Efficiency).
