### ISSUE TITLE
[request] randomizer

### ISSUE THREAD

**Issue by mskiller** [wolfden/ComfyUi_PromptStylers#4]
A choice below base, that says random so it choose randomly one of the style installed. Then when you launch 10 prompt in queue it will choose each time a different style. And if you put the png file back in it should show the style that was chosen.

**Comment by wolfden** [comment]
Hi, yea that is beyond my coding skills, first thing that comes to mind is a wildcard text file.  

ComfyUI\custom_nodes\ComfyUI-Impact-Pack\wildcards is where you can store wildcard txt files, create a txt file then use the wildcard node and put in the name of the text file ( example horror2.txt ) then put like __horror2__ and it will randomly pick a line from that file.  You could even have it do more lines from same file with __horror2_, __horror2__, __horror2__ and with each queue it would grab 3 random lines.  See txt file.   Anyway, I don't know if putting the pic back in will give you the prompt.
[horror2.txt](https://github.com/wolfden/ComfyUi_PromptStylers/files/12851165/horror2.txt)
![Screenshot 2023-10-09 182344](https://github.com/wolfden/ComfyUi_PromptStylers/assets/30942/04345e8c-b09c-46dc-b03c-e43cc86c4585)

**Comment by mskiller** [comment]
Thank you, I thought that like random seeds you could give à number to the style and call up that number. I will take a deeper look inti wildcards then...but I will also look into tour code to see if I find à way and will propose it to you.

**Comment by wolfden** [comment]
I messed around and able to get this working with each run now.  As far as putting the png file back in and getting the prompt? I don't know.  I ran across a github that had a node you could add to get the images info, forgot the name of it now.  git pull to get latest changes



![Screenshot 2023-10-22 163947](https://github.com/wolfden/ComfyUi_PromptStylers/assets/30942/9548e9af-656f-4d93-80cd-4bc0b39cb5cf)
![Screenshot 2023-10-22 162635](https://github.com/wolfden/ComfyUi_PromptStylers/assets/30942/9a1d4c04-c627-4a85-8bdf-ddb0f127c518)
